name: generate snake animation

on:
  schedule:
    - cron: "23 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=0f766e&color_dots=#e7ebef,#a7d8d1,#5bb0a6,#2a8c80,#0f766e
            dist/github-snake-dark.svg?color_snake=2dd4bf&color_dots=#1c232c,#14453f,#1a7a6d,#22a996,#2dd4bf

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
